version: "3.9"  # optional since v1.27.0
services:
  interface:
    build: ./interface
    ports:
      - "5000:3000"
  api:
    build: ./api
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
volumes:
  mongo: 